import Sidebar from "@/components/shared/Sidebar"

import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col bg-[white] overflow-hidden h-screen md:flex-row">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  )
}
